import sys

file_path = r'c:\Users\John Carlo\OneDrive\Desktop\startupevent\startuplab-business-ticketing\frontend\views\User\UserEvents.tsx'

with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

new_lines = lines[:1873] + [
    "                        </div> {/* Close main editor center panel */}\n",
    "\n",
    "                        {/* Preview Right Panel */}\n",
    "                        {isPreviewMode && (\n",
    "                             <div className=\"hidden xl:block fixed top-[73px] bottom-0 right-0 w-[45%] border-l border-[#2E2E2F]/15 bg-white overflow-y-auto z-10\">\n",
    "                                <div className=\"p-10\">\n",
    "                                     <div className=\"max-w-[600px] mx-auto overflow-hidden bg-white border border-[#2E2E2F]/15 rounded-2xl shadow-2xl transition-all duration-500 hover:shadow-3xl transform\">\n",
    "                                         {/* Preview Header Banner */}\n",
    "                                         <div className=\"relative aspect-video bg-[#F2F2F2]\">\n",
    "                                             {formData.coverImage || formData.imageUrl ? (\n",
    "                                                 <img src={getImageUrl(formData.coverImage || formData.imageUrl)} alt=\"Cover\" className=\"w-full h-full object-cover\" />\n",
    "                                             ) : (\n",
    "                                                 <div className=\"w-full h-full flex items-center justify-center border-b border-[#2E2E2F]/10\">\n",
    "                                                     <div className=\"flex flex-col items-center\">\n",
    "                                                         <div className=\"w-16 h-16 rounded-2xl bg-white shadow-sm flex items-center justify-center mb-3 border border-[#2E2E2F]/10\">\n",
    "                                                             <ICONS.Image className=\"w-6 h-6 text-[#2E2E2F]/30\" />\n",
    "                                                         </div>\n",
    "                                                         <p className=\"text-[10px] font-bold text-[#2E2E2F]/40 uppercase tracking-widest\">Upload Cover Image</p>\n",
    "                                                     </div>\n",
    "                                                 </div>\n",
    "                                             )}\n",
    "                                             <div className=\"absolute top-4 right-4 w-8 h-8 rounded-full bg-white/90 shadow flex items-center justify-center text-[#2E2E2F]/40 cursor-pointer hover:text-[#2E2E2F]\">\n",
    "                                                 <ICONS.Share2 className=\"w-4 h-4\" />\n",
    "                                             </div>\n",
    "                                         </div>\n",
    "\n",
    "                                         <div className=\"p-8\">\n",
    "                                             <div className=\"flex gap-4 items-start mb-6\">\n",
    "                                                 <div className=\"flex flex-col items-center justify-center w-[60px] h-[60px] rounded-xl border border-[#2E2E2F]/10 bg-[#F9F9FB] shrink-0\">\n",
    "                                                    <span className=\"text-[10px] font-black text-[#e85d04] uppercase tracking-wide leading-none mb-1\">\n",
    "                                                        {formData.startDate ? new Date(formData.startDate).toLocaleDateString('en-US', { month: 'short' }) : 'MON'}\n",
    "                                                    </span>\n",
    "                                                    <span className=\"text-xl font-black text-[#2E2E2F] leading-none\">\n",
    "                                                        {formData.startDate ? new Date(formData.startDate).getDate() : '27'}\n",
    "                                                    </span>\n",
    "                                                 </div>\n",
    "                                                 <div>\n",
    "                                                     <h2 className=\"text-3xl font-black text-[#2E2E2F] leading-tight mb-2 tracking-tight\">\n",
    "                                                         {formData.eventName || 'Event Title'}\n",
    "                                                     </h2>\n",
    "                                                     <p className=\"text-sm font-medium text-[#2E2E2F]/60 max-w-sm leading-relaxed\">\n",
    "                                                         {formData.description || 'A short and sweet sentence about your event.'}\n",
    "                                                     </p>\n",
    "                                                 </div>\n",
    "                                             </div>\n",
    "\n",
    "                                             <div className=\"space-y-4 mb-8\">\n",
    "                                                 <div className=\"p-5 rounded-xl border border-[#2E2E2F]/10 flex items-start gap-4\">\n",
    "                                                     <div className=\"mt-0.5 w-8 h-8 rounded-full bg-[#f8f9fa] flex items-center justify-center text-[#2E2E2F]/60\">\n",
    "                                                         <ICONS.Calendar className=\"w-4 h-4\" />\n",
    "                                                     </div>\n",
    "                                                     <div>\n",
    "                                                         <p className=\"text-xs font-bold text-[#2E2E2F] mb-1\">Date and time</p>\n",
    "                                                         <p className=\"text-sm text-[#2E2E2F]/70\">{previewDateLabel === 'Select Dates' ? 'Monday, April 27 · 10am - 12pm PST' : previewDateLabel}</p>\n",
    "                                                     </div>\n",
    "                                                 </div>\n",
    "                                                 <div className=\"p-5 rounded-xl border border-[#2E2E2F]/10 flex items-start gap-4\">\n",
    "                                                     <div className=\"mt-0.5 w-8 h-8 rounded-full bg-[#f8f9fa] flex items-center justify-center text-[#2E2E2F]/60\">\n",
    "                                                         <ICONS.MapPin className=\"w-4 h-4\" />\n",
    "                                                     </div>\n",
    "                                                     <div>\n",
    "                                                         <p className=\"text-xs font-bold text-[#2E2E2F] mb-1\">Location</p>\n",
    "                                                         <p className=\"text-sm text-[#2E2E2F]/70\">{formData.location || 'Enter a location'}</p>\n",
    "                                                     </div>\n",
    "                                                 </div>\n",
    "                                             </div>\n",
    "                                         </div>\n",
    "                                     </div>\n",
    "                                </div>\n",
    "                             </div>\n",
    "                        )}\n",
    "                    </div>\n",
    "                </div>\n",
    "            )}\n",
] + lines[2118:]

with open(file_path, 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

print("Done")
